<?php
/**
 * ============================================================
 * ISLAMIC WEBSITE - Islamic Calendar Page
 * Premium Islamic Web Application
 * ============================================================
 */

define('ACCESS_ALLOWED', true);
require_once __DIR__ . '/includes/config.php';

define('PAGE_TITLE', 'Islamic Calendar');
define('META_DESCRIPTION', 'Islamic Hijri calendar with Gregorian dates. View Islamic events, important dates, and celebrations.');

include __DIR__ . '/includes/header.php';

$hijriDate = getHijriDate();
?>

<!-- ============================================
PAGE HEADER
============================================ -->
<section class="page-header">
    <div class="container">
        <div class="page-header-content">
            <h1 class="page-title">Islamic Calendar</h1>
            <nav class="page-breadcrumb">
                <a href="index.php">Home</a>
                <span class="separator">/</span>
                <span>Islamic Calendar</span>
            </nav>
        </div>
    </div>
</section>

<section class="calendar-page">
    <div class="container">
        <div class="calendar-header">
            <div class="hijri-date-display" id="hijriDateDisplay">
                <?php echo sanitizeOutput($hijriDate['display']); ?>
            </div>
            <div class="gregorian-date-display" id="gregorianDateDisplay">
                <?php echo date('l, F j, Y'); ?>
            </div>
        </div>
        
        <!-- Calendar Navigation -->
        <div class="d-flex" style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 24px;">
            <button class="btn btn-ghost btn-sm" id="calendarPrev">
                <i class="fas fa-chevron-left"></i> Previous
            </button>
            <h3 id="calendarMonthDisplay" style="font-size: 1.2rem; font-weight: 700; color: var(--primary-dark);">
                <?php echo date('F Y'); ?>
            </h3>
            <button class="btn btn-ghost btn-sm" id="calendarNext">
                Next <i class="fas fa-chevron-right"></i>
            </button>
        </div>
        
        <!-- Calendar Grid -->
        <div class="calendar-grid" id="calendarGrid">
            <!-- Generated by JavaScript -->
        </div>
        
        <!-- Islamic Events -->
        <div class="islamic-events">
            <h3 class="events-title">
                <i class="fas fa-star" style="color: var(--gold);"></i>
                Islamic Events & Holidays
            </h3>
            <div id="islamicEventsList">
                <!-- Generated by JavaScript -->
            </div>
        </div>
        
        <!-- Month Info -->
        <div class="glass-card" style="margin-top: 24px;">
            <h3 style="font-size: 1.1rem; font-weight: 700; margin-bottom: 12px; color: var(--primary-dark);">
                <i class="fas fa-moon"></i> About the Islamic Calendar
            </h3>
            <p style="font-size: 0.95rem; color: var(--gray); line-height: 1.8;">
                The Islamic calendar (Hijri calendar) is a lunar calendar consisting of 12 months in a year of 354 or 355 days. 
                It is used to determine the proper days of Islamic holidays and rituals, such as the annual period of fasting and the proper time for Hajj.
            </p>
            <div style="margin-top: 12px; display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; font-size: 0.85rem;">
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Muharram</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Safar</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Rabi' al-Awwal</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Rabi' al-Thani</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Jumada al-Awwal</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Jumada al-Thani</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Rajab</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Shaban</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Ramadan</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Shawwal</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Dhul Qa'dah</span>
                <span style="background: var(--off-white); padding: 8px; border-radius: var(--radius-sm); text-align: center;">Dhul Hijjah</span>
            </div>
        </div>
    </div>
</section>

<?php
$extraScripts = [JS_PATH . 'pages/calendar.js'];
include __DIR__ . '/includes/footer.php';
?>
